name: url_audio_stream
description: Flutter/Dart plugin to live stream a URL
version: 1.0.0+2
author: tcronis <tcronist@gmail.com>
homepage: https://github.com/tcronis/url_audio_stream

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:
  plugin:
    androidPackage: com.example.url_audio_stream
    pluginClass: UrlAudioStreamPlugin