name: url_audio_stream
description: A new flutter plugin project.
version: 1.0.0+1
author: tcronis (Tyler)
homepage: https://github.com/tcronis

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:
  plugin:
    androidPackage: com.example.url_audio_stream
    pluginClass: UrlAudioStreamPlugin